# Base image — lightweight nginx
FROM nginx:alpine

# Remove default nginx page
RUN rm -rf /usr/share/nginx/html/*

# Copy frontend files
COPY index.html /usr/share/nginx/html/

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Health check
HEALTHCHECK --interval=30s \
            --timeout=10s \
            --retries=3 \
    CMD wget -q --spider \
    http://localhost:80 || exit 1

CMD ["nginx", "-g", "daemon off;"]